Feature: namespace BQ metadata field when provided
gojek/beast pull request #64
Opened 2020-10-19 12:26 UTC by rootcss

when `BQ_METADATA_NAMESPACE=` config is set to some value, namespace the kafka offset metadata in BQ i.e, as a RECORD/STRUCT type.

By default, the value will be empty, which means metadata fields will be written as different columns rather than a RECORD/STRUCT type.

2020-10-21 06:10 UTC, rootcss commented on src/main/java/com/gojek/beast/protomapping/ProtoUpdateListener.java
> +            bqSchemaFields.addAll(bqMetadataFields);
check for collision with all the metadata fields

2020-10-21 10:42 UTC, rootcss commented
@sravankorumilli Please review and merge.

2020-10-23 05:34 UTC, mauliksoneji requested changes

2020-10-23 10:37 UTC, rootcss commented on src/test/java/com/gojek/beast/converter/ConsumerRecordConverterIntegrationTest.java
> +        assertEquals(record1ExpectedColumns.size(), record1Columns.size());
Oops, Removed it.

2020-10-23 10:37 UTC, rootcss commented on src/test/java/com/gojek/beast/converter/ConsumerRecordConverterIntegrationTest.java
> +        assertEquals(record1ExpectedColumns.size(), record1Columns.size());
Oops, Removed it.

2020-10-26 12:01 UTC, mauliksoneji approved these changes

2020-10-26 12:01 UTC, merged